### ISSUE TITLE
qr_painter.dart, Null check operator used on a null value

### ISSUE THREAD

**Issue by masterwok** [lukef/qr.flutter#223]
**Describe the bug**

Version: 4.1.0

Observing the following stack-trace in production DataDog logs:

```
#0 replaceFirstNull (/Users/vagrant/.pub-cache/hosted/pub.dev/source_span-1.10.0/lib/src/utils.dart:39)
#0 Highlighter.highlight (/Users/vagrant/.pub-cache/hosted/pub.dev/source_span-1.10.0/lib/src/highlighter.dart:224)
#1 QrPainter._initPaints (/Users/vagrant/.pub-cache/hosted/pub.dev/qr_flutter-4.1.0/lib/src/qr_painter.dart:183)
```

**To Reproduce**

Haven't been able to reproduce this issue locally.

**Expected behavior**

Should guard against null reference exception.

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS: iOS

**Smartphone (please complete the following information):**
 - Device: iOS
 - OS: 17.5.1

**Additional context**

n/a

**Comment by masterwok** [comment]
I believe the line numbers from the trace above aren't accurate and the issue is occuring here:

https://github.com/theyakka/qr.flutter/blob/d5e7206396105d643113618290bbcc755d05f492/lib/src/qr_painter.dart#L148
