### ISSUE TITLE
QrPainter.paint error in Android

### ISSUE THREAD

**Issue by BaojunCZ** [lukef/qr.flutter#34]
I used [qr_flutter](https://pub.dartlang.org/packages/qr_flutter) to show mnemonic.

## Code
```
import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';

class Test extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _State();
}

class _State extends State<Test> {
  bool isLoading = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: isLoading
            ? CircularProgressIndicator()
            : Center(
                child: QrImage(
                  data:
                      'often rotate million nasty  size angle phrase celery rookie simple borrow fabric',
                  size: 200,
                ),
              ));
  }
}
```

## Log
```
I/flutter (15120): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15120): The following assertion was thrown during paint():
I/flutter (15120): Failed assertion: boolean expression must not be null
I/flutter (15120): 
I/flutter (15120): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15120): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15120): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15120):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (15120): 
I/flutter (15120): When the exception was thrown, this was the stack:
I/flutter (15120): #0      QrPainter.paint (package:qr_flutter/src/qr_painter.dart:71:17)
I/flutter (15120): #1      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:521:13)
I/flutter (15120): #2      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:559:7)
I/flutter (15120): #3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #5      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (15120): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #11     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:222:15)
I/flutter (15120): #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #14     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (15120): #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #17     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (15120): #18     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter (15120): #19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #22     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:504:11)
I/flutter (15120): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #26     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1737:88)
I/flutter (15120): #27     ClipContext._clipAndPaint (package:flutter/src/painting/clip.dart:29:12)
I/flutter (15120): #28     ClipContext.clipRRectAndPaint (package:flutter/src/painting/clip.dart:49:5)
I/flutter (15120): #29     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1737:17)
I/flutter (15120): #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #37     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (15120): #38     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (15120): #39     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter (15120): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter (15120): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #44     RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:910:17)
I/flutter (15120): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #48     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2448:13)
I/flutter (15120): #49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #53     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (15120): #54     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (15120): #55     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter (15120): #56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter (15120): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #61     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3045:11)
I/flutter (15120): #62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #64     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (15120): #65     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:594:5)
I/flutter (15120): #66     RenderStack.paint (package:flutter/src/rendering/stack.dart:602:7)
I/flutter (15120): #67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #69     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #79     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2629:11)
I/flutter (15120): #80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #83     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:562:11)
I/flutter (15120): #84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15120): #87     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #88     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (15120): #89     RenderView.paint (package:flutter/src/rendering/view.dart:182:15)
I/flutter (15120): #90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (15120): #91     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (15120): #92     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (15120): #93     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:853:29)
I/flutter (15120): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:331:19)
I/flutter (15120): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (15120): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (15120): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (15120): #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (15120): #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
I/flutter (15120): #108    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (15120): #109    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (15120): #110    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (15120): (elided 8 frames from package dart:async)
I/flutter (15120): 
I/flutter (15120): The following RenderObject was being processed when the exception was fired:
I/flutter (15120):   RenderCustomPaint#52fda
I/flutter (15120):   creator: CustomPaint ← Padding ← ConstrainedBox ← Container ← LayoutBuilder ← QrImage ← Center ←
I/flutter (15120):   MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ←
I/flutter (15120):   DefaultTextStyle ← ⋯
I/flutter (15120):   parentData: offset=Offset(10.0, 10.0) (can use size)
I/flutter (15120):   constraints: BoxConstraints(w=180.0, h=180.0)
I/flutter (15120):   size: Size(180.0, 180.0)
I/flutter (15120): This RenderObject has no descendants.
```

**Comment by BaojunCZ** [comment]
It`s too long
